### ISSUE TITLE
Maximum call stack exceeded

### ISSUE THREAD

**Issue by dulichan** [hew/react-scroll-horizontal#10]
When I have only 3 slides or less - I get the below error when I try to scroll. Any idea why this is coming?

Uncaught RangeError: Maximum call stack size exceeded

**Comment by hew** [comment]
The logic that holds the sliding component 'in place' relies on the child/children being wider than parent. If you only have three slides, it might not be wide enough. 

You bring up a good point, though, which is that I should do a check to ensure that the child is wider than the parent.

**Comment by TimJin** [comment]
I had the same problem. after some debug here is what I did
if (curr >= 1) {//change to curr < 0
      this.resetMin()
    } else if (curr <= bounds) {//change to curr > bounds
      var x = bounds + 1
      this.resetMax(x)
    }

**Comment by hew** [comment]
Yeah... I wrote this code when I first got into programming/open source. It really, really needs a re-write. I'm currently working some pretty long hours at a startup so I haven't had the time.

**Comment by hew** [comment]
Fixed w/ https://github.com/hew/react-scroll-horizontal/releases/new?tag=v1.1.3
