### ISSUE TITLE
Provide a button for manual scrolling

### ISSUE THREAD

**Issue by enlego** [hew/react-scroll-horizontal#11]
I'm trying to trigger a WheelEvent for manual scrolling with a button.
Have you thought in providing some manual button for scrolling? I have some users that don't naturally scroll and are expecting a button to move around.

Tranks!

**Comment by hew** [comment]
Yes I actually implemented a button-based approach a little while back for a project. I will see if I can locate that code. But the basic idea is you just emulate mouse deltas manually. So the button would add however many units to state that you want to move. The code for this lib is actually fairly simple in some ways. It's just a funnel.

Mouse deltas --> state --> React Motion

So you would want:

Button +100px --> state --> React Motion

**Comment by jgentes** [comment]
Would love to see this if you have it, also would be great to allow scrolling with touch on a mobile web browser.

**Comment by hew** [comment]
I'm going to close this, as I doubt I'll ever implement a button. This lib specializes in mouse events.
