### ISSUE TITLE
Can't resolve 'react-motion'

### ISSUE THREAD

**Issue by jgentes** [hew/react-scroll-horizontal#12]
First attempt to import and use HorizontalScroll resulted in this error:

`Module not found: Error: Can't resolve 'react-motion' in '...\node_modules\react-scroll-horizontal\dist'`

Installing `react-motion` via npm fixed the problem. Is this a dependency that should be included?

**Comment by gretzky** [comment]
[Merged](https://github.com/hew/react-scroll-horizontal/pull/13)

**Comment by hew** [comment]
I forgot to push the new release to NPM. Use the Github version in the interim.

**Comment by hew** [comment]
New version out: https://github.com/hew/react-scroll-horizontal/releases/tag/1.1.2

Should fix the above errors.

**Comment by zachgibson** [comment]
@hew Seeing this issue with version 1.2.0:
```zsh
This dependency was not found:

* react-motion in ./~/react-scroll-horizontal/dist/react-scroll-horizontal.js

To install it, you can run: npm install --save react-motion
```

**Comment by hew** [comment]
@zachgibson I see the issue (I think). I'll push up another release asap.

**Comment by hew** [comment]
@zachgibson Ok this release should fix that issue. 
https://github.com/hew/react-scroll-horizontal/releases/tag/v1.2.1

**Comment by zachgibson** [comment]
@hew Nice! Thanks dude.
