### ISSUE TITLE
module not found 'react-scroll-horizontal'

### ISSUE THREAD

**Issue by Liqiankun** [hew/react-scroll-horizontal#14]

**Comment by Liqiankun** [comment]
![2017-05-09 2 55 10](https://cloud.githubusercontent.com/assets/11532418/25838822/89ca8cc6-34c7-11e7-8b0a-f66ecf534ec3.png)

**Comment by raissanorth** [comment]
That appears to be a simple typo in the demo code provided. Try `import HorizontalScroll from 'react-scroll-horizontal'` instead.

**Comment by hew** [comment]
Yes @raissanorth is correct. Mistake in the Readme. I had to change the name after I discovered that 'react-horizontal-scroll' was taken. I have corrected the Readme. Thanks.

**Comment by Liqiankun** [comment]
Thank you! I should spend more time on Readme! @raissanorth @hew

**Comment by Liqiankun** [comment]
I figured it out! 
```
npm i react-horizontal-scroll --save
```
```
import HorizontalScroll from 'react-horizontal-scroll'
```
Then it works!

**Comment by Liqiankun** [comment]
But It still do not give me what I want!

**Comment by raissanorth** [comment]
You might want to read the comment from @hew again and pay attention to the name of the module. You actually installed a different one. This module is called react-scroll-horizontal. Hence you need to use `npm install react-scroll-horizontal` and the import statement I mentioned earlier.

**Comment by Liqiankun** [comment]
@raissanorth Thanks! I will give it a shot!

**Comment by hew** [comment]
New version (1.1.2) out: https://github.com/hew/react-scroll-horizontal/releases/tag/1.1.2
