### ISSUE TITLE
Doesn't support percentages

### ISSUE THREAD

**Issue by sadzebra** [hew/react-scroll-horizontal#18]
I know this is in the documentation but we know the reason it doesn't work with percentages maybe a plan of action to support it?

It would be a handy feature.

**Comment by hew** [comment]
This would be achieved by doing a runtime check for for the length of the parent element, and then translate the mouse deltas to be a pixel/em representation of the percentage of the length. 

That's how I would do it, I think.

**Comment by hew** [comment]
I'll attempt this at some point, but if anyone wants to take a crack at it, PRs are welcome.

**Comment by sadzebra** [comment]
I'm thinking about giving it ago but it's a case of finding some time to spend on it.
