### ISSUE TITLE
Crazy "shiver" behaviour when zoomed out

### ISSUE THREAD

**Issue by ThatBrianDude** [hew/react-scroll-horizontal#19]
https://imgur.com/a/RzCHH

In the GIF its less visible but the shivering is actually much faster then it looks. Whenever Im zoomed out and the content is in the center of the scroll area I am NOT scrolling with my mouse. The back and forth behaviour came from nothing. 

EDIT: if it means anything, I had to remove react v15 from the node modules folder of the "react-scroll-horizontal" module because I got the "You may have multiple copies of React loaded" error before. After removing react and react-dom it worked fine.

I have react v16 installed

**Comment by hew** [comment]
Interesting. 

I suspect that we maybe need to re-render/re-calculate on browser magnification. (Not sure if there is an event for that.) Does that behaviour occur only with magnification?

**Comment by MelMepham** [comment]
I am having this issue when I am scrolling with my mouse.. starts shivering like the gif, it doesn't stop until I refresh the page...

**Comment by MelMepham** [comment]
oohh ok, on that note, its only when I don't have enough children to do the horizontal scroll. easy fix, add more elements, but something to note.

**Comment by hew** [comment]
Agreed. I've made a more emphasized note in the Readme. Thanks!
