### ISSUE TITLE
react 16 report an error

### ISSUE THREAD

**Issue by chenjinxinlove** [hew/react-scroll-horizontal#22]
Error in /turbo_modules/fbjs@0.8.16/lib/invariant.js:
Element ref was specified as a string (hScrollParent) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).
Evaluating index.js

https://stackblitz.com/edit/react-yjxusz?embed=1&file=index.js

**Comment by jorgemarrero** [comment]
The same for me.

**Comment by hew** [comment]
I haven't gotten around to pushing an update to this library for React 16. But string refs are a pretty old thing. In the meantime, you might want to start with converting those to functions, maybe. It seems that string refs w/o a parent might not be allowed anymore.

**Comment by hew** [comment]
New release out with function refs. This maybe fix your issue. https://github.com/hew/react-scroll-horizontal/releases/tag/v1.2.0

**Comment by hew** [comment]
Gonna close this, as it's been inactive for a while. Feel free to comment if this is still happening, and I'll open'r up again.
