### ISSUE TITLE
'react-scroll'horizontal' not being recognized for react 16

### ISSUE THREAD

**Issue by MohammadHasham** [hew/react-scroll-horizontal#23]
The component doesn't seem to be imported.As if packages are not installed.

**Comment by hew** [comment]
Hmm. Need more info.

**Comment by MohammadHasham** [comment]
when i try 
`import ReactHorizontalBar from react-horizontal-bar`

The error says, cannot find 'react-horizontal-bar'

**Comment by hew** [comment]
Hmm, that syntax won't work (the name is incorrect). You will want to try 

`import HorizontalScroll from 'react-scroll-horizontal'`
