### ISSUE TITLE
Question: How to Handle Responsive

### ISSUE THREAD

**Issue by MelMepham** [hew/react-scroll-horizontal#25]
Hey, so I am using this, and I am wondering how I can make it responsive, I know that the width and height have to be defined, so does that mean responsiveness isn't really a thing without a heap of media queries?

**Comment by hew** [comment]
@MelMepham The best bet for responsive would be to try `vw`. Keep in mind also that the restriction is just for the parent, so you could maybe have a mixture of 100% parent with some kind of treatment for the children. Hope this helps!
