### ISSUE TITLE
Buttons in the horizontal scroll will always revert back to the beginning of the scroll

### ISSUE THREAD

**Issue by MelMepham** [hew/react-scroll-horizontal#26]
I have a page full of images that have onClicks on them, every time one of the buttons is pressed it reverts back to the beginning, I found the translate that is moving the scroll. but if I try and set the state of that it seems to be overrided by something in the base code..

**Comment by zachgibson** [comment]
@MelMepham Looking through the source I’d guess maybe [this code](https://github.com/hew/react-scroll-horizontal/blob/master/src/react-scroll-horizontal.js#L83) is reseting your translate.
```JSX
componentWillReceiveProps(nextProps) {
    if (this.props.children !== nextProps.children) {
      // Reset container offset
      this.resetMin()
    }
  }
```
If you make a [CodeSandbox](https://codesandbox.io/) I’d be happy to take a look.

**Comment by MelMepham** [comment]
Yup, that is totally what it was, a good point of code to note if it happens for anyone else. I deleted that line of code and it hasn't had any other negative effects yet..

**Comment by zachgibson** [comment]
@MelMepham I’m wary of deleting code where I don’t know it’s purpose. 😜 Maybe @hew can weigh in on what this code does?

**Comment by hew** [comment]
I can't remember, but I suspect we can delete it. Looking at the code, it seems like https://github.com/hew/react-scroll-horizontal/blob/master/src/react-scroll-horizontal.js#L32 will handle new children. I don't see any point in resetting the scroll back to the beginning also.

**Comment by MelMepham** [comment]
Yup, I have had no issues. Should I make a pull request to delete this?

**Comment by hew** [comment]
Yes that would be great, thanks.

**Comment by lemonadecreative** [comment]
Hey guys. Removing `this.resetMin()` worked for me as well, in my case. Will this be updated in a new version, or how do you suggest implementing this for future upgrades?

Thanks

**Comment by hew** [comment]
@lemonadecreative, and everyone else. @MelMepham's PR has been merged, and the new release can be found here: https://github.com/hew/react-scroll-horizontal/releases/tag/v1.3.0. Thanks everyone for your contributions.

**Comment by hew** [comment]
Note: please use [1.3.1](https://github.com/hew/react-scroll-horizontal/releases/tag/v1.3.1) for the above.
