### ISSUE TITLE
Expose interpolatedStyle

### ISSUE THREAD

**Issue by zachgibson** [hew/react-scroll-horizontal#27]
My use-case needs to animate more than just translation. It’d be great to have `interpolatedStyle` exposed to children of `HorizontalScroll `. I’d be happy to implement this if you’re down.

**Comment by hew** [comment]
Sure @zachgibson - go for it 😎

**Comment by zachgibson** [comment]
I realized something. Access to interpolatedStyle won’t be as useful without a way to say *when* you want to animate a specific item. My example was going to animate some other transform property like rotation in addition to the original horizontal translation, but I would want to animate it when the item is in view. I could possibly write some “in view” logic to enable or disable the animation. Not sure.

**Comment by hew** [comment]
It's experimental, but we could maybe try `intersectionObserver` to determine if a child is in view.

**Comment by zachgibson** [comment]
Yeah I’m curious if that would work and what it would look like. Coming from React Native land, we have a method called interpolate that solves issues like this. Don’t know if it would be possible with React Motion, but it’d be really nice.

e.g.
```JSX
<HorizontalScroll>
  {animVal =>
    CARDS.map((card, i) => (
      <Card
        style={{
          transform: `rotate(${animVal.interpolate({
            inputRange: [i * CARD_WIDTH, (i + 1) * CARD_WIDTH],
            outputRange: ['45deg', '0deg'],
          })})`,
        }}
      />
    ))
  }
</HorizontalScroll>
```

**Comment by hew** [comment]
I kinda forgot we were still in the middle of this. I merged your PR, but we can continue hashing out the rest of the functionality. https://github.com/hew/react-scroll-horizontal/pull/30
