### ISSUE TITLE
Not mobile responsive

### ISSUE THREAD

**Issue by MelMepham** [hew/react-scroll-horizontal#28]
So I have used this scroll, for a website I am making (checkout aplaceofdreams.herokuapp.com) - but its not mobile responsive, I am interested in learning how to do this, and adding to this module to make it a feature, would anyone have any ideas on where to start looking?

**Comment by zachgibson** [comment]
@MelMepham You can use [react-draggable](https://github.com/mzabriskie/react-draggable). I did this already but didn’t PR it. Basically you wrap this component with Draggable and `onDrag` you set state. e.g. this.state.animValues + deltaX. The weird thing was, you need to explicitly disable dragging via draggable so draggable won’t move your UI—you’re relying on react-scroll-horizontal to do that.

**Comment by quinnliu** [comment]
@zachgibson Thanks 4 the comment. R u able 2 show some example code of what u mean exactly? I'm having trouble implementing what u mean. This is what I have so far. Thanks.

```javascript
	render() {
		return (
			<div>
				<Draggable
					axis="x"
					onDrag={this.updateState()}
					disabled={true}>
					{this.renderGameCard()} // <== I want my multiple Game Cards 2 b able 2 scroll horizontally
				</Draggable>
			</div>
		);
	}
```

```javascript
	updateState() {
		const deltaX = 5;
		console.log("this.state.animValues= ", this.state.animValues)
		//this.setState({ animValues: this.state.animValues + deltaX });
	}
```

```javascript
	state = {
		animValues: 0
	}
```

**Comment by jjalonso** [comment]
Will be great to post it as component or PR.

**Comment by jimmynames** [comment]
+1 for @zachgibson code share or PR/Comp <3
