### ISSUE TITLE
Its not working for me

### ISSUE THREAD

**Issue by tailornirmal** [hew/react-scroll-horizontal#32]
Code  :

`import React, { Component } from 'react';
import HorizontalScroll from 'react-scroll-horizontal'

class Scroll extends Component {
  render() {
    return (
      <div>
        <HorizontalScroll>
            <div style={{width : '300px',height : '300px'}} />
        </HorizontalScroll>
      </div>
    );
  }

}

export default Scroll;`

TypeError: _this4.props.children is not a function.

React version 16. please let me know what is the exact issue ?

**Comment by tailornirmal** [comment]
![error](https://user-images.githubusercontent.com/39124868/42322791-63d71010-807b-11e8-9721-c866f87c5f73.png)

**Comment by hew** [comment]
Hey @tailornirmal, 

This lib is designed to allow you to scroll the children of a parent div (horizontally). So, there will need to be children present. That is the error that you are getting there. Admittedly, I should handle this better in the code. 

I will open an issue for this. Thanks for your report!

**Comment by hew** [comment]
Gonna close this one for now. As I said above, thanks for the report!
