### ISSUE TITLE
Better no children error handling

### ISSUE THREAD

**Issue by hew** [hew/react-scroll-horizontal#33]
As per https://github.com/hew/react-scroll-horizontal/issues/32, we should better handle a lack of children with some error handling.

**Comment by Nickadiemus** [comment]
Could really use this package in my personal portfolio but It doesn't seem to work when trying to render by your examples. getting a specific error on 

```      
  var scrollingElementStyles = {
              transform: 'translate3d(' + z + 'px, 0,0)',
              display: 'inline-flex',
              height: '100%',
              position: 'absolute',
              willChange: 'transform'
            };
            debugger;
            return _react2.default.createElement(              
              'div',
              { style: scrollingElementStyles },
              _this4.props.children(z) <- this line
            );
          }
```

**Comment by hew** [comment]
@Nickadiemus  Just pushed a new version that fixes your issue. https://github.com/hew/react-scroll-horizontal/releases/tag/v1.5.0
