### ISSUE TITLE
Add react-draggable?

### ISSUE THREAD

**Issue by kimborgen** [hew/react-scroll-horizontal#35]
Hi! 

First off, loving your project. 

As mobile support is a *must* these days it is sad that this project does not support it. I would like to have one component for one "feature" if you know what i mean.

I've been able to include react-draggable and react-scroll-horizontal in my own project. And it seems to work pretty good! But it was not as easy as I would like.

**Is integrating react-draggable in this project a feature you would like?** @hew 
And something that I should try solving?

Alternativly we can just add a detailed entry in the readme on how to integrate the two projects.

## Previous work
I saw that in #4 you allready tried this approch, any luck there? @zachgibson seems to have made progress on this (#4 & #28), but has not submitted a PR. 

## General Approch:
1. When dragging you get a delta x from draggable. (But no dragging / moving is happening because we disable that)
2. This delta x is passed down to the HorizontalScroll component on the new prop animValues (See PR #36 )
3. The horizontal scroll component then does it's thing as if a scroll had just happend by updating the state variable animValues with the new prop and then calculating new motion.
4. Profit.

**Comment by JonathanWi** [comment]
Interested as well, any chance you could share your implementation somewhere and/or create a PR with it?

**Comment by kimborgen** [comment]
@JonathanWi 

Hi, I did not want to start working on a feature before it was confirmed that this was something the project maintainer wanted. So i have not made any PR yet.

In order to implement react-draggable this project needs to merge #36. Since this is not done yet (The project maintainer seems inactive) you can pull this from my project: https://github.com/kimborgen/react-scroll-horizontal

In order to add this project with npm you can either do something with npm link (google it, I don't remember how i did it) or take a look at this: https://stackoverflow.com/questions/33181297/npm-install-from-github-pull-request 

And in order to add react-draggable, you can look at my personal project here: https://github.com/kimborgen/kimborgen.com/blob/master/src/components/instafeed/InstaFeed.jsx

**Comment by hew** [comment]
Hey everyone. Sorry for the late response. 

> Is integrating react-draggable in this project a feature you would like?

I don't think so. I'd rather just leave the animProp from your PR open (nice work on that btw) so that the scroll can be solved in user space. But I'd 100% be for a note in the PR that shows how to integrate `react-scrollable`.
