### ISSUE TITLE
Grey background when adding the scroll around my components

### ISSUE THREAD

**Issue by nats12** [hew/react-scroll-horizontal#37]
Hi, I keep getting just a grey screen when trying to work this. It won't scroll vertically (as it did before adding the scroll) nor horizontally. I've made sure I have enough projects to notice the scroll as one wouldn't make a difference. Please find code snippet below:

<img width="565" alt="screenshot 2018-11-07 at 22 46 17" src="https://user-images.githubusercontent.com/15801768/48165903-fb356e00-e2de-11e8-8aa9-a5f90f517c46.png">

Any ideas?

**Comment by hew** [comment]
My guess here would be the styles as being the culprit. Are the children rendered, if you check the DOM nodes (in the browser inspector)?
