### ISSUE TITLE
Add Null Checks for Elements

### ISSUE THREAD

**Issue by Tsury** [hew/react-scroll-horizontal#40]
I just started using this library so I don't have much info to give, but it's maybe worth adding some null check for `el` there if you can't find it in the DOM.

```
TypeError: Cannot read property 'lastElementChild' of null
  at apply(./node_modules/react-scroll-horizontal/dist/index.es.js:1738:1)
  at n(./node_modules/@sentry/browser/dist/index.js:3114:1)
```

![image](https://user-images.githubusercontent.com/4947581/50571339-a1b66080-0db0-11e9-9abd-9465d90d7ac0.png)

**Comment by hew** [comment]
Yes that is a good idea. 

I'm curious - what is that error reporting tool you are using? Looks cool.

**Comment by Tsury** [comment]
It's Sentry. Hands down best error reporting system.

**Comment by hew** [comment]
Need to add some basic null checks. This would be a good first contribution issue.
