### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by mkunevicius** [hew/react-scroll-horizontal#6]
I get this:
(https://facebook.github.io/react/warnings/refs-must-have-owner.html)

Is that because I use react@15.2.1 and maybe try to get react@0.14.8 with your dependencies when npm installing 'react-scroll-horizontal'?

Any ideas?

**Comment by hew** [comment]
I don't think so, as I have the dependency for this library at React v15+. 

If it's a refs thing, I suspect that it has something to do with [this area](https://github.com/hew/react-scroll-horizontal/blob/master/src/react-scroll-horizontal.js#L31) of the code.

**Comment by mkunevicius** [comment]
OK, thanks, but still have no idea of workaround...

**Comment by hew** [comment]
I just downloaded this repo and did a fresh install. I don't see the issue you are running into. 

Do you have any sample code that I can take a look at?

**Comment by mkunevicius** [comment]
Whatever you did, I don't get that warning anymore (didn't change my code). Thanks. Now just have to figure out why the content is not shown inside <Horizontalscroll> (data comes OK). What I do wrong?

`import React, { Component } from 'react'
import HorizontalScroll from 'react-scroll-horizontal'

class Gallery extends Component {
  render() {
    const child = { width: `300em`, height: `100%` }
    return (
      <div>
        <HorizontalScroll>
            {this.props.images.map((image, i) =>
              <div style={child} className='imageContainer' key={i}>
                <img className='image' src={`/${image.imagePath}`} />
              </div>
            )}
        </HorizontalScroll>
      </div>
    )
  }
}

export default Gallery`

**Comment by mkunevicius** [comment]
Thank you! Whatever you did, now it doesn't throw that warning.
I only have problems with reverseScroll: 
Warning: Unknown prop `reverseScroll` on `div` tag.
And sth to do with:
Uncaught (in promise) RangeError: Maximum call stack size exceeded

(https://github.com/mkunevicius/Dratele/blob/master/app/components/Gallery.js)

**Comment by hew** [comment]
I was able to replicate your issue. Thanks for the report! 😸 

I'm not sure what's up, but I pushed this lib to github without any proptypes, which is kind of a no-no. I'll add proptypes and tidy things up a bit, and I suspect I'll spot the issue. 

I'll be able to get to this within a couple of days.

**Comment by hew** [comment]
Hey @mkunevicius please try again with the newest version (0.0.6).

It should fix the issue you are having.

**Comment by mkunevicius** [comment]
It seems like everything works perfect now, thank you!

**Comment by hew** [comment]
Thanks for reporting! 👌🏽👏🏽
