### ISSUE TITLE
Cannot resolve 'react-motion'

### ISSUE THREAD

**Issue by josephdburdick** [hew/react-scroll-horizontal#8]
Hi, great plugin! I was recreating something just like this from scratch and stumbled upon this. I'm interested in leveraging this but it I've come across the following error:
```
ERROR in ./~/react-scroll-horizontal/dist/react-scroll-horizontal.js
Module not found: Error: Cannot resolve module 'react-motion' in /Users/jb/Sites/Joey/node_modules/react-scroll-horizontal/dist
 @ ./~/react-scroll-horizontal/dist/react-scroll-horizontal.js 19:19-42
```

I've looked into your `package.json` and it appears you've left wildcards `*` for version numbers  of some your dependencies. This will request the latest and greatest but it opens your plugin to the possibility of breaking changes.

**Comment by hew** [comment]
Interesting. This *should* work even with the wildcards. This isn't a breaking change so much as module resolution issue. I would say the easy fix here is to just install react-motion. It may have been uninstalled as a dependency for some other package. 

I am slightly new to library creation/maintenance, so please excuse any errant mistakes. You are right I probably should not be using wildcards.

**Comment by josephdburdick** [comment]
As it turns out, it's because you had it listed in devDependencies instead of dependencies. I've made a pull request as seen above.

**Comment by hew** [comment]
Ah. Yes that makes sense. Nice work! 👏
