### ISSUE TITLE
Not able to active the  pageLock= {bool}

### ISSUE THREAD

**Issue by cyruslk** [hew/react-scroll-horizontal#80]
Hey, thanks for this great package! 

Here's my code:
```
     horizontalPageDesktop = () => {
       if(this.props.isSeeAll){
         return null;
       }else{
         if(this.state.renderProjectInfo){
           return (
             <div>
               <div id="container">
                 {this.renderProjectMedia()}
               </div>
           </div>
           )
         }else{
           return (
               <div>
                 <div
                   id="container_2">
                   {this.renderButtonCloseInfo()}
                   <HorizontalScroll
                     pageLock={true}
                     className = { "horizontal_scroll" }
                     reverseScroll = {true}>
                     {this.renderProjectMedia()}
                    </HorizontalScroll>
                 </div>
             </div>
           )
         }
       }
    }
```
When I implement the pageLock, I see the the body is `locked__ `. However I I'm not able to fully lock your component with css nor JavaScript. I filled a StackOverflow issue [here](https://stackoverflow.com/questions/57858182/not-able-to-lock-transform-translate3d-when-blocking-the-html-tag) with my attempts. What do you suggest so that I can avoid the `transform: translate3d();` to occur?

**Comment by cyruslk** [comment]
I see that it triggers the HTML. However I'm not able to block your components with CSS. What tricks do you suggest? Thank you.

**Comment by hew** [comment]
Hmm. This issue is pretty old. I suspect you have either moved on from this project, or found a solution.

Gonna close for now. Feel free to re-open.
