### ISSUE TITLE
linked demo doesn't work

### ISSUE THREAD

**Issue by sajhu** [hew/react-scroll-horizontal#81]
Hey 

so I came across this plugin seaching for an horinzontal solution, opened the demo and it didn't scroll, either with the mosewheel nor while dragging

**Comment by hew** [comment]
Yeah I noticed that recently — at least in Safari. 

I'm currently looking for a maintainer for this project. It needs a lot of love, and I'm currently too busy with work to really dedicate any time to a re-write. If anyone reading this is interested, let me know.

**Comment by hew** [comment]
Fixed w/ https://github.com/hew/react-scroll-horizontal/pull/84

**Comment by hew** [comment]
> nor while dragging

Note: this lib doesn't support dragging.
