### ISSUE TITLE
Unable to preventDefault inside passive event listener

### ISSUE THREAD

**Issue by KirDontsov** [hew/react-scroll-horizontal#82]
How to clear this err?

[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312

**Comment by hew** [comment]
Should be fixed w/ https://github.com/hew/react-scroll-horizontal/pull/84. 

Re-open if not.

**Comment by KirDontsov** [comment]
Yeah, fixed now, thank you very much! Your repo with draggable addition, is a great thing, now working on mobile, and looks amazing! )

**Comment by hew** [comment]
@KirDontsov Glad it's working out! If you can share a link, I'd love to see it in action.

**Comment by KirDontsov** [comment]
Sure, here is the test link, later it would be a small e-shop in Russia, I'll rework design a little bit, but the basic concept is on the horizontal scroll ))
[http://martinz.rainbows23.tmweb.ru/](url) @hew

**Comment by hew** [comment]
@KirDontsov Love it! Looks great.
