### ISSUE TITLE
HorizontalScroll Wheeling Error

### ISSUE THREAD

**Issue by baymax88** [hew/react-scroll-horizontal#87]
When I scroll the mouse, it shows the error like the following video.
https://www.loom.com/share/c541583c6e4e476c86b3d54841b59c7b
As you can see, if there are fewer child components, it is not finding where the child should be placed but vibrating.
It seems I need to set the option when the sum of the width of children is less than the parent component's width.

Please let me know how I can fix this issue.

**Comment by benkhlifafahmi** [comment]
any update ?

**Comment by hew** [comment]
The video is gone, but as noted in the README, the width of the children must be greater than the width of the scroll container (or there's nothing to scroll).
