### ISSUE TITLE
Reaching the end of the horizontal scroll container

### ISSUE THREAD

**Issue by AshleighRefresh** [hew/react-scroll-horizontal#91]
Hi there

I'd just like to find out if there is a way to tell when you've reached the end of the horizontal scroll container?
I saw the PR which has not yet been merged in, so just wanted to find out if there is a work around that I could use for now?

Thanks!

**Comment by hew** [comment]
@AshleighRefresh Yeah that PR had some git conflicts that I wasn't too keen fixing, so I'm re-writing the lib completely. V2 will have the `onEnd`, `onBeginning`, etc callbacks so you can know when you are at the end. 

If you are in a pinch, just clone the PR branch and use that, as others have.
