### ISSUE TITLE
Scroll event listener doesn’t work for horizontal

### ISSUE THREAD

**Issue by samhren** [hew/react-scroll-horizontal#98]
Event listener for window doesn’t trigger on ‘scroll’ when scrolling horizontal. And the documentation doesn’t explain how animValues work. So what would be the solution here, trying to animate my background when in a certain part of my site.

**Comment by hew** [comment]
Scrolling in the area of the page that the library is handling won't trigger any scroll events because the overflow is hidden in the parent element. If you provide some code, I can try to help you out with your implementation.

**Comment by samhren** [comment]
I am just wondering if there is a way to get the current position you are on the site. I am attempting to create an animated background that plays when you scroll over a certain part. But it impossible if the scroll events wont trigger.
